### ISSUE TITLE
[ALIGNED CHATBOX] becomes unaligned and rounded when using the PartyMode plugin in vencord

### ISSUE THREAD

**Issue by modraws** [CodeF53/CSS-Snippets#4]
![image](https://github.com/user-attachments/assets/82ab3086-78b3-4609-b533-acc1b3bbcb46)

**Comment by modraws** [comment]
also the combo meter is placed above the chatbox, but never displays the combo

**Comment by CodeF53** [comment]
Just don't use the partymode plugin. Adding support for this would be super confusing when I maintain this in the future
